### ISSUE TITLE
Example for chain

### ISSUE THREAD

**Issue by yonifra** [wix-incubator/carmi#165]
Here is my Example for [chain](https://carmi.js.org/api.html#doc-1755):
  ```javascript
    const { root } = require('carmi');
    const input = [{boss: 'or'}, {slaves: ['oded']}];
    chain([{boss: 'sivan', slaves: [root.get(1).get('slaves').get(0), root.get(0).get('boss')]}]).assign();
  ```

**Comment by LeonFedotov** [comment]
Hey @yonifra thanks so much for you contribution!
Ive taken your example and modified it a bit to make it more accessible to people outside WIX and matched it for the example api, let me know if it works for you, cheers!

```javascript
const { root, chain } = require('carmi');
const instance = fromSource({
    output: chain([{shelf: root.get(0).get('shelf'), books: [root.get(1).get(root.get(0).get('shelf')).get(0)]}]).assign()
}, [{shelf: 'scifi'}, {scifi: ['a scanner darkly']}]);
instance.output //true

```

**Comment by yonifra** [comment]
I have more examples for other APIs, so I can add them to the repo if you'd like (doing the tutorial now)

**Comment by LeonFedotov** [comment]
sounds good, i would like to have the examples trough the issues so we could curate the overall style, besides the publishing process is clunky and i'm doing it manually for now so its not a big deal, do you mind just submitting them? 
I really don't like the examples in the tutorial, i mean i know its jokes about the team but its just confusing, i propose we use a library metaphor like in the example iv'e created above, 
alright?

**Comment by yonifra** [comment]
Sure 👍

**Comment by LeonFedotov** [comment]
#181 will include this, Cheers ^_^
