### ISSUE TITLE
Problem with types on latest typescript (3.5),  New typescript fails with error

### ISSUE THREAD

**Issue by LeonFedotov** [wix-incubator/carmi#212]
Pr thats adding a `@ts-ignore` is in place until we figure this out -> #211 
`
Error:(358, 75) TS2344: Type ‘UnionToIntersection<Value>’ does not satisfy the constraint ‘object’.
`
cc: @noamr

**Comment by LeonFedotov** [comment]
Maybe @AviVahl can provide some insights.

**Comment by AviVahl** [comment]
insights:
typescript changed their type handling in the past 2 versions quite a lot. many places that used to default to `{}` now default to unknown. I guess this caused the error.
I'll try finding the relevant PR.

**Comment by LeonFedotov** [comment]
Great stuff! Thank you @AviVahl, @idok I think we found our issue :)
Cc @noamr

**Comment by noamr** [comment]
Oh interesting. Yes, I would suggest using {} in Carmi typings instead of object.

**Comment by LeonFedotov** [comment]
@noamr unfortunately this didn't do the trick. any more ideas? (#222)
