### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by LeonFedotov** [wix-incubator/carmi#213]
@idok can you please provide recommendations?

**Comment by idok** [comment]
run yarn upgrade-interactive --latest

**Comment by LeonFedotov** [comment]
new pr #221 !

**Comment by LeonFedotov** [comment]
theres one problem left with `babel-plugin-tester` maybe @avi can take a look? it seems that since babel updated its plugin api we are doing something illegal from the plugin standpoint...
